

return {

  research_tiers = 6,

  simple_modifiers_default_tier =
    {
      count=0,
      value="",
      prereqs = "",
      cost_inputs="",
      cost_count="",
      cost_time=1,
      icon="",
      order="a",
    },

  simple_modifiers =
    {
      ["inserter-stack-size-bonus"] = {
        [6] = {
          count=-1,
          value=1,
          prereqs = "inserter-capacity-bonus-7, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="2^L*5000",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
      },

      ["stack-inserter-capacity-bonus"] = {
        [6] = {
          count=-1,
          value=1,
          prereqs = "inserter-capacity-bonus-7, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*5000",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
      },

      ["laboratory-speed"] = {
        [6] = {
          count=-1,
          value=1,
          prereqs = "research-speed-6, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*5000",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
      },

      ["character-logistic-slots"] = {}, -- Not infinite but already set to huge in vanilla...

      ["character-logistic-trash-slots"] = {}, -- Not infinite but already set to huge in vanilla...

      ["maximum-following-robots-count"] = {}, -- Infinite vanilla already

      ["worker-robot-speed"] = {}, -- Infinite vanilla already

      ["worker-robot-storage"] = {
        [6] = {
          count=-1,
          value=1,
          prereqs = "worker-robots-storage-3, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="2^L*1000",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
      },

      ["ghost-time-to-live"] = {}, -- Not infinite but already set to huge in vanilla...

      ["character-crafting-speed"] = {
        [1] = {
          count=10,
          value=0.05,
          prereqs = "automation",
          cost_inputs="science-pack-1",
          cost_count="L*10",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=15,
          value=0.1,
          prereqs = "<prior>, automation-2",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*50",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=5,
          value=0.2,
          prereqs = "<prior>, automation-3",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*200",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=2,
          value=0.5,
          prereqs = "<prior>, automation-4",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*500",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=2,
          value=0.5,
          prereqs = "<prior>, automation-5",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*400",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=0.1,
          prereqs = "<prior>, automation-6, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*500",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["character-mining-speed"] = {
        [1] = {
          count=10,
          value=0.05,
          prereqs = "optics",
          cost_inputs="science-pack-1",
          cost_count="L*10",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=15,
          value=0.1,
          prereqs = "<prior>, mining-productivity-1",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*50",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=5,
          value=0.2,
          prereqs = "<prior>, mining-productivity-4",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*200",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=2,
          value=0.5,
          prereqs = "<prior>, mining-productivity-8",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*500",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=2,
          value=0.5,
          prereqs = "<prior>, mining-productivity-12",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*400",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=0.1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*500",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["character-running-speed"] = {
        [1] = {
          count=10,
          value=0.05,
          prereqs = "logistics",
          cost_inputs="science-pack-1",
          cost_count="L*10",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=15,
          value=0.1,
          prereqs = "<prior>, logistics-2",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*50",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=5,
          value=0.2,
          prereqs = "<prior>, logistics-3",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*200",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=2,
          value=0.5,
          prereqs = "<prior>, logistics-4",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*500",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=2,
          value=0.5,
          prereqs = "<prior>, logistics-5",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*400",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=0.1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*500",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["character-build-distance"] = {
        [1] = {
          count=10,
          value=1,
          prereqs = "logistics, automation",
          cost_inputs="science-pack-1",
          cost_count="L*10",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=15,
          value=1,
          prereqs = "<prior>, logistics-2, stack-inserter",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*50",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=20,
          value=1,
          prereqs = "<prior>, logistics-3",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*75",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=25,
          value=1,
          prereqs = "<prior>, logistics-4",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*100",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=30,
          value=1,
          prereqs = "<prior>, logistics-5",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*150",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*200",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["character-item-drop-distance"] = {
        [1] = {
          count=10,
          value=1,
          prereqs = "logistics, automation",
          cost_inputs="science-pack-1",
          cost_count="L*10",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=15,
          value=1,
          prereqs = "<prior>, logistics-2, stack-inserter",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*50",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=20,
          value=1,
          prereqs = "<prior>, logistics-3",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*75",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=25,
          value=1,
          prereqs = "<prior>, logistics-4",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*100",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=30,
          value=1,
          prereqs = "<prior>, logistics-5",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*150",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*200",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["character-reach-distance"] = {
        [1] = {
          count=10,
          value=1,
          prereqs = "logistics, automation",
          cost_inputs="science-pack-1",
          cost_count="L*10",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=15,
          value=1,
          prereqs = "<prior>, logistics-2, stack-inserter",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*50",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=20,
          value=1,
          prereqs = "<prior>, logistics-3",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*75",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=25,
          value=1,
          prereqs = "<prior>, logistics-4",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*100",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=30,
          value=1,
          prereqs = "<prior>, logistics-5",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*150",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*200",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["character-resource-reach-distance"] = {
        [1] = {
          count=10,
          value=1,
          prereqs = "logistics, automation",
          cost_inputs="science-pack-1",
          cost_count="L*10",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=15,
          value=1,
          prereqs = "<prior>, logistics-2, stack-inserter",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*50",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=20,
          value=1,
          prereqs = "<prior>, logistics-3",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*75",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=25,
          value=1,
          prereqs = "<prior>, logistics-4",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*100",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=30,
          value=1,
          prereqs = "<prior>, logistics-5",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*150",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*200",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["character-item-pickup-distance"] = {}, -- Eh, unsure if want to increase these by default...

      ["character-loot-pickup-distance"] = {}, -- Eh, unsure if want to increase these by default...

      ["character-inventory-slots-bonus"] = {
        [1] = {
          count=5,
          value=2,
          prereqs = "heavy-armor",
          cost_inputs="science-pack-1",
          cost_count="L*100",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=5,
          value=2,
          prereqs = "overmods-research_modifier-character-inventory-slots-bonus-1-1, modular-armor",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*200",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=5,
          value=2,
          prereqs = "<prior>, power-armor",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*250",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=5,
          value=2,
          prereqs = "<prior>, military-3",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*logistic-science-pack, 1*military-science-pack",
          cost_count="L*300",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=5,
          value=2,
          prereqs = "<prior>, power-armor-2",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*military-science-pack, 1*production-science-pack, 1*high-tech-science-pack",
          cost_count="L*400",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*military-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*500",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["deconstruction-time-to-live"] = {}, -- Unsure what this would do...

      ["character-health-bonus"] = {
        [1] = {
          count=5,
          value=10,
          prereqs = "heavy-armor",
          cost_inputs="science-pack-1",
          cost_count="L*100",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=5,
          value=20,
          prereqs = "<prior>, modular-armor",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*200",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=4,
          value=25,
          prereqs = "<prior>, power-armor",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*military-science-pack",
          cost_count="L*250",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=4,
          value=25,
          prereqs = "<prior>, military-3",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*military-science-pack, 1*science-pack-3",
          cost_count="L*300",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=10,
          value=20,
          prereqs = "<prior>, power-armor-2",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*military-science-pack, 2*science-pack-3, 1*production-science-pack, 1*high-tech-science-pack",
          cost_count="L*400",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=10,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*military-science-pack, 2*logistic-science-pack, 2*science-pack-3, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*500",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["auto-character-logistic-trash-slots"] = {}, -- Already in vanilla

      ["mining-drill-productivity-bonus"] = {}, -- Already in vanilla

      ["train-braking-force-bonus"] = {}, -- Vanilla adds up to 100 here, maybe already maxed, unsure about tiny infinites...

      ["zoom-to-world-enabled"] = {}, -- Unsure what this would do...

      ["zoom-to-world-ghost-building-enabled"] = {}, -- Unsure what this would do...

      ["zoom-to-world-blueprint-enabled"] = {}, -- Unsure what this would do...

      ["zoom-to-world-deconstruction-planner-enabled"] = {}, -- Unsure what this would do...

      ["zoom-to-world-selection-tool-enabled"] = {}, -- Unsure what this would do...

      ["worker-robot-battery"] = {
        [1] = {
          count=10,
          value=0.025,
          prereqs = "robotics, battery",
          cost_inputs="science-pack-1",
          cost_count="L*100",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=10,
          value=0.05,
          prereqs = "<prior>",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*150",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=10,
          value=0.075,
          prereqs = "<prior>, battery-2",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*200",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=10,
          value=0.1,
          prereqs = "<prior>",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*250",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=20,
          value=0.1,
          prereqs = "<prior>, logistics-5, battery-3",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*300",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=0.1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*1000",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["laboratory-productivity"] = {
        [1] = {
          count=10,
          value=0.025,
          prereqs = "steel-processing, military, optics, stone-walls, logistics, turrets, electronics",
          cost_inputs="science-pack-1",
          cost_count="L*150",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=10,
          value=0.05,
          prereqs = "<prior>, circuit-network, advanced-electronics, modules, military-2, logistics-2",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*200",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=10,
          value=0.075,
          prereqs = "<prior>, battery, logistics-3, automobilism, military-3",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3, 1*military-science",
          cost_count="L*250",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=10,
          value=0.1,
          prereqs = "<prior>, nuclear-power, logistics-4, effect-transmission",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 2*military-science, 1*logistic-science-pack, 1*production-science-pack",
          cost_count="L*300",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=20,
          value=0.1,
          prereqs = "<prior>, logistics-5, battery-3, kovarex-enrichment-process",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 4*military-science, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*500",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=0.1,
          prereqs = "<prior>, rocket-silo, atomic-bomb",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*1000",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },

      ["follower-robot-lifetime"] = {
        [1] = {
          count=10,
          value=0.025,
          prereqs = "robotics, battery",
          cost_inputs="science-pack-1",
          cost_count="L*100",
          cost_time=15,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "a",
        },
        [2] = {
          count=10,
          value=0.05,
          prereqs = "<prior>",
          cost_inputs="2*science-pack-1, 1*science-pack-2",
          cost_count="L*150",
          cost_time=30,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "b",
        },
        [3] = {
          count=10,
          value=0.075,
          prereqs = "<prior>, battery-2",
          cost_inputs="4*science-pack-1, 2*science-pack-2, 1*science-pack-3",
          cost_count="L*200",
          cost_time=45,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "c",
        },
        [4] = {
          count=10,
          value=0.1,
          prereqs = "<prior>",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 2*science-pack-3, 1*production-science-pack",
          cost_count="L*250",
          cost_time=60,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "d",
        },
        [5] = {
          count=20,
          value=0.1,
          prereqs = "<prior>, logistics-5, battery-3",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*production-science-pack, 1*logistic-science-pack, 1*high-tech-science-pack",
          cost_count="L*300",
          cost_time=90,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "e",
        },
        [6] = {
          count=-1,
          value=0.1,
          prereqs = "<prior>, rocket-silo",
          cost_inputs="4*science-pack-1, 4*science-pack-2, 4*science-pack-3, 2*logistic-science-pack, 2*production-science-pack, 2*high-tech-science-pack, 1*space-science-pack",
          cost_count="L*1000",
          cost_time=120,
          icon = "__base__/graphics/technology/worker-robots-storage.png",
          order = "f",
        },
      },
    },

  -- Non-Simple Modifiers:
  -- "ammo-damage"
  -- "gun-speed"
  -- "give-item"
  -- "turret-attack"
  -- "unlock-recipe"
  -- "nothing"

}
